name: 'test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: has-label
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: deploy,foo,bar
      - if: ${{ steps.has-label.outputs.result == 'true' }}
        run: |
          echo 'true'
      - if: ${{ steps.has-label.outputs.result == 'false' }}
        run: |
          echo 'false'
